export { SectionAbout } from './About'
export { SectionExperience } from './Experience'
export { SectionGetInTouch } from './GetInTouch'
export { SectionHero } from './Hero'
export { SectionProject } from './Project'
